name: bucketlist
description: "A Flutter application for managing and sharing bucket lists with friends and family."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7  # Updated to match Android versionCode

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_app_check: ^0.3.2+7  # Updated to latest available version for Play Integrity API
  mobile_scanner: ^6.0.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2  # Add path_provider for local file storage
  qr_flutter: ^4.1.0
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_commons: ^0.9.0
  google_mlkit_barcode_scanning: ^0.13.0
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  # Using an alternative modern navigation package
  salomon_bottom_bar: ^3.3.2
  # AdMob Integration
  google_mobile_ads: ^5.1.0
  # Environment variables
  flutter_dotenv: ^5.1.0
  # FlutterFlow-style utilities and animations
  flutter_animate: ^4.2.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.6.0
  # SVG support for generated avatars
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # Add this line
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

# Add the flutter_launcher_icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"  # or any color you prefer
  adaptive_icon_foreground: "assets/images/logo.png"
  web:
    generate: false
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: false
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: false
    image_path: "assets/images/logo.png"
